
Rails.application.config.assets.precompile += %w( font-awesome.css )
Rails.application.config.assets.precompile += %w( responsive.css )
Rails.application.config.assets.precompile += %w( skins.css )
Rails.application.config.assets.precompile += %w( jquery.min.js )
Rails.application.config.assets.precompile += %w( html5.js )
Rails.application.config.assets.precompile += %w( jquery.nicescroll.min.js )
Rails.application.config.assets.precompile += %w( tabs.js )
Rails.application.config.assets.precompile += %w( jquery.prettyPhoto.js )
Rails.application.config.assets.precompile += %w( jquery.bxslider.min.js )
Rails.application.config.assets.precompile += %w( jquery.tweet.js )
Rails.application.config.assets.precompile += %w( jflickrfeed.min.js )
Rails.application.config.assets.precompile += %w( jquery.jribbble-1.0.1.ugly.js )
Rails.application.config.assets.precompile += %w( custom.js )